name = "ALifeBenchmark"
uuid = "439d69cc-e0bf-49d0-b082-3f737e8414aa"
authors = ["Tobia Ochsner <tobia.ochnser@hotmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
