const AXIOM_NODES = ["001", "000", "01"]
const DELETED = "del"

const NOISE_LEVEL = 0.6
const EXCITATORY_MIN = 0
const EXCITATORY_MAX = 2
const INHIBITORY_THRESHOLD = 0.5

const FIGHT_THRESHOLD = 0.565
const CROSS_OVER_THRESHOLD = 0.3
const INFLUENCE_RADIUS = 2

const MUTATION_PROBABILITY = 1e-2

const MAX_NEURONS = 80