const AXIOM_NODES = ["001", "000", "01"]
const DELETED = "del"

const NOISE_LEVEL_NODES = 0.6
const NOISE_LEVEL_MISSING_OUTPUT = 0.5
const EXCITATORY_MIN = 0
const EXCITATORY_MAX = 2
const INHIBITORY_THRESHOLD = 0.5

const MAX_TURN = 60

const FIGHT_THRESHOLD = 0.5
const CROSS_OVER_THRESHOLD = 0.5
const INFLUENCE_RADIUS = 2

const DISTANCE_SCALE_FACTOR = 4

const MUTATION_PROBABILITY = 0

const MAX_NEURONS = 20
const MIN_ORGANISMS = 0 # 20
const MAX_DEVELOPMENT_STEPS = 99