const MUTATE = true
const COSMIC_RAYS_PROBABILITY = 1e-9
const FLAW_PROBABILITY = 1e-4

const NUM_THREADS = 4
const SLICE_SIZE = 10

const MAX_SEARCH_DISTANCE = 256
const MAX_TEMPLATE_LENGTH = 16

const MIN_DAUGHTER_SIZE = 8
const MAX_DAUGHTER_GROWTH = 4

const MAX_MEMORY_CAPACITY = 0.5
